#!/usr/bin/env php
<?php

echo PHP_EOL .
    '===========================================================' . PHP_EOL . PHP_EOL .
    '  ____  _              ____ ____ ____    _     _       _   ' . PHP_EOL .
    ' |  _ \| |__  _ __    / ___/ ___/ ___|  | |   (_)_ __ | |_ ' . PHP_EOL .
    " | |_) | '_ \| '_ \  | |   \___ \___ \  | |   | | '_ \| __|" . PHP_EOL .
    ' |  __/| | | | |_) | | |___ ___) |__) | | |___| | | | | |_ ' . PHP_EOL .
    ' |_|   |_| |_| .__/   \____|____/____/  |_____|_|_| |_|\__|' . PHP_EOL .
    '             |_|                                           ' . PHP_EOL . PHP_EOL .
    '===========================================================' . PHP_EOL . PHP_EOL;

$composerAutoloaderWorkingDirectory = getcwd() . '/vendor/autoload.php';
if (is_file($composerAutoloaderWorkingDirectory)) {
    require_once $composerAutoloaderWorkingDirectory;
}

if (!class_exists('CssLint\CssLint', true)) {
    // consider being in bin dir
    $composerAutoloader = __DIR__ . '/../vendor/autoload.php';
    if (!is_file($composerAutoloader)) {
        // consider being in vendor/neilime/php-css-lint/scripts
        $composerAutoloader = __DIR__ . '/../../../autoload.php';
    }

    require_once $composerAutoloader;
}

$cssLintCli = new \CssLint\Cli();
$returnCode = $cssLintCli->run($_SERVER['argv']);

exit($returnCode);
